/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import Banco.Inserir;
import Banco.Selecionar;
import Classes.Criptografia;
import Classes.ODB_Anexo;
import Classes.ODB_Parameter;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class FrmAnexo extends javax.swing.JFrame {

    /**
     * Creates new form FrmAnexo
     */
    public FrmAnexo() {
        initComponents();
        DgAnexos.getParent().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        TxNomeCurso = new javax.swing.JTextField();
        TxCPFCurso = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        BtNovo = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtBuscarLista = new javax.swing.JButton();
        TxCaminho = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        BtCaminho = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DgAnexos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ANEXOS");
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMAÇÕES ADICIONAIS"));
        jPanel3.setLayout(null);

        jLabel24.setText("CAMINHO");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(10, 90, 150, 16);

        TxNomeCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNomeCursoKeyReleased(evt);
            }
        });
        jPanel3.add(TxNomeCurso);
        TxNomeCurso.setBounds(170, 60, 350, 22);

        TxCPFCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCPFCursoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxCPFCursoKeyPressed(evt);
            }
        });
        jPanel3.add(TxCPFCurso);
        TxCPFCurso.setBounds(10, 60, 150, 22);

        jLabel43.setText("NOME");
        jPanel3.add(jLabel43);
        jLabel43.setBounds(170, 40, 60, 16);

        BtNovo.setBackground(new java.awt.Color(255, 255, 255));
        BtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo.png"))); // NOI18N
        BtNovo.setToolTipText("NOVO");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });
        jPanel3.add(BtNovo);
        BtNovo.setBounds(540, 100, 38, 40);

        BtExcluir.setBackground(new java.awt.Color(255, 255, 255));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Excluir.png"))); // NOI18N
        BtExcluir.setToolTipText("EXCLUIR");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(BtExcluir);
        BtExcluir.setBounds(540, 60, 40, 40);

        BtBuscarLista.setBackground(new java.awt.Color(255, 255, 255));
        BtBuscarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Listar.png"))); // NOI18N
        BtBuscarLista.setToolTipText("BUSCAR");
        jPanel3.add(BtBuscarLista);
        BtBuscarLista.setBounds(540, 20, 38, 40);
        jPanel3.add(TxCaminho);
        TxCaminho.setBounds(10, 110, 490, 22);

        jLabel25.setText("CPF");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(10, 40, 60, 16);

        BtCaminho.setBackground(new java.awt.Color(255, 255, 255));
        BtCaminho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        BtCaminho.setToolTipText("BUSCAR");
        BtCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCaminhoActionPerformed(evt);
            }
        });
        jPanel3.add(BtCaminho);
        BtCaminho.setBounds(500, 110, 20, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 20, 610, 150);

        DgAnexos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CAMINHO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DgAnexos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 610, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxNomeCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeCursoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxNomeCurso.setText(TxNomeCurso.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxNomeCursoKeyReleased

    private void TxCPFCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFCursoKeyTyped
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxCPFCursoKeyTyped

    private void TxCPFCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFCursoKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){

                String Retorno = Selecionar.Consultar_CPFDetetive(Criptografia.Cripto(TxCPFCurso.getText()));

                if(Retorno.equals("")){
                    throw new Exception("DETETIVE NÃO ENCONTRADO, FAVOR VERIFIQUE");
                }else{
                    TxNomeCurso.setText(Retorno);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxCPFCursoKeyPressed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        try{

            ODB_Anexo _anexo = new ODB_Anexo();
            
            File arquivo = new File (TxCaminho.getText()); 
            
            _anexo.setCodigoDetetive(Selecionar.Consultar_IDDetetive(Criptografia.Cripto(TxCPFCurso.getText())));
            _anexo.setArquivo(arquivo);
            
            Inserir.Criar_DetetiveAnexo(_anexo);

        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,"A DATA DEVE ESTA NO FORMATO (dd/MM/yyyy), FAVOR VERIFIQUE","ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try
        {

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCaminhoActionPerformed
        try{
            JFileChooser chooser = new JFileChooser();
             chooser.showOpenDialog(null);
             
             File file = chooser.getSelectedFile();
             String Caminho = file.getAbsolutePath();
             
             TxCaminho.setText(Caminho);
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,"A DATA DEVE ESTA NO FORMATO (dd/MM/yyyy), FAVOR VERIFIQUE","ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtCaminhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnexo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAnexo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarLista;
    private javax.swing.JButton BtCaminho;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovo;
    private javax.swing.JTable DgAnexos;
    private javax.swing.JTextField TxCPFCurso;
    private javax.swing.JTextField TxCaminho;
    private javax.swing.JTextField TxNomeCurso;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
