/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import Banco.Selecionar;
import Classes.ODB_Usuarios;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class FrmConsultarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsultarUsuarios
     */
    public FrmConsultarUsuarios() {
        initComponents();
        DgUsuarios.getParent().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DgUsuarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxDescricao = new javax.swing.JTextField();
        ChEmail = new javax.swing.JCheckBox();
        BtConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ChNome = new javax.swing.JCheckBox();
        ChCPF = new javax.swing.JCheckBox();
        ChTudo = new javax.swing.JCheckBox();
        BtFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTAR LIBERAÇÃO DE USUÁRIOS");
        getContentPane().setLayout(null);

        DgUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "USUARIO", "CPFCNPJ", "ENTIDADE", "TELEFONE", "EMAIL", "LIBERADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DgUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DgUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DgUsuarios);
        if (DgUsuarios.getColumnModel().getColumnCount() > 0) {
            DgUsuarios.getColumnModel().getColumn(0).setPreferredWidth(200);
            DgUsuarios.getColumnModel().getColumn(1).setPreferredWidth(120);
            DgUsuarios.getColumnModel().getColumn(2).setPreferredWidth(100);
            DgUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);
            DgUsuarios.getColumnModel().getColumn(4).setPreferredWidth(100);
            DgUsuarios.getColumnModel().getColumn(5).setPreferredWidth(150);
            DgUsuarios.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 770, 380);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("O que deseja fazer"));
        jPanel1.setLayout(null);

        jLabel1.setText("DESCRIÇÃO");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 30, 150, 16);
        jPanel1.add(TxDescricao);
        TxDescricao.setBounds(200, 50, 370, 22);

        ChEmail.setBackground(new java.awt.Color(255, 255, 255));
        ChEmail.setText("EMAIL");
        jPanel1.add(ChEmail);
        ChEmail.setBounds(100, 60, 81, 20);

        BtConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        BtConsultar.setBorder(null);
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(BtConsultar);
        BtConsultar.setBounds(590, 40, 40, 40);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("FILTRAR")));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 180, 70);

        ChNome.setBackground(new java.awt.Color(255, 255, 255));
        ChNome.setText("NOME");
        jPanel1.add(ChNome);
        ChNome.setBounds(20, 40, 80, 20);

        ChCPF.setBackground(new java.awt.Color(255, 255, 255));
        ChCPF.setText("CPF");
        jPanel1.add(ChCPF);
        ChCPF.setBounds(20, 60, 81, 20);

        ChTudo.setBackground(new java.awt.Color(255, 255, 255));
        ChTudo.setText("TUDO");
        jPanel1.add(ChTudo);
        ChTudo.setBounds(100, 40, 81, 20);

        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGINS.png"))); // NOI18N
        BtFechar.setToolTipText("FECHAR");
        BtFechar.setBorder(null);
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        jPanel1.add(BtFechar);
        BtFechar.setBounds(640, 40, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 770, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtFecharActionPerformed

     public void limpaTabela(){
        if(model.getRowCount() > 0){
            for( int i = model.getRowCount() - 1; i >= 0; i-- )
             {
                 model.removeRow(i);
             }
        }

    }
     
     private DefaultTableModel model;
     
    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        try{
            
            model = (DefaultTableModel)DgUsuarios.getModel();
            
            if(ChNome.isSelected()){
                if(TxDescricao.getText().equals(""))
                {
                    throw new Exception("INFORME O NOME DO USUÁRIO");
                }else{
                    
                }
            }else if(ChCPF.isSelected()){
                 if(TxDescricao.getText().equals(""))
                {
                    throw new Exception("INFORME O CPF DO USUÁRIO");
                }else{
                    
                }
            }else if(ChEmail.isSelected()){
                 if(TxDescricao.getText().equals(""))
                {
                    throw new Exception("INFORME O EMAIL DO USUÁRIO");
                }else{
                    
                }
            }else if(ChTudo.isSelected()){
                
                this.limpaTabela();
                
                ArrayList<ODB_Usuarios> Listar_Usuarios = Selecionar.Listar_Usuarios();
                String[] param = new String[7];
                
                for(int i = 0; i < Listar_Usuarios.size(); i++){
                    
                    param[0] = Listar_Usuarios.get(i).getNome();
                    param[1] = Listar_Usuarios.get(i).getUsuario();
                    param[2] = Listar_Usuarios.get(i).getCPFCNPJ();
                    param[3] = Listar_Usuarios.get(i).getEntidade();
                    param[4] = String.valueOf(Listar_Usuarios.get(i).getTelefone());
                    param[5] = Listar_Usuarios.get(i).getEmail();
                    param[6] = Listar_Usuarios.get(i).getLiberado().toString();
                    
                    model.addRow(param);
                }
            }else{
                throw new Exception("FAVOR SELECIONE UMA DAS OPÇÕES AO LADO");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtConsultarActionPerformed

    private void DgUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DgUsuariosMouseClicked
        try{
            String opcoes[] = new String[]{"Atualizar", "Excluir", "Liberar"};
            
            if (evt.getClickCount() == 1){
                int i = JOptionPane.showOptionDialog(null, "O QUE DESEJA FAZER?", "ALERTA", -1, -1, null, opcoes, 0);
                
                switch (i) {
                    case 0:
                        break;
                    case 1:
                        break;
                    default:
                        break;
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_DgUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmConsultarUsuarios().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtFechar;
    private javax.swing.JCheckBox ChCPF;
    private javax.swing.JCheckBox ChEmail;
    private javax.swing.JCheckBox ChNome;
    private javax.swing.JCheckBox ChTudo;
    private javax.swing.JTable DgUsuarios;
    private javax.swing.JTextField TxDescricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
