/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import Banco.Inserir;
import Banco.Selecionar;
import Classes.Criptografia;
import Classes.ODB_Cursos;
import Classes.ODB_Parameter;
import Classes.ODB_Validador;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class FrmCurso extends javax.swing.JFrame {

    /**
     * Creates new form FrmCurso
     */
    public FrmCurso() {
        initComponents();
        DgCurso.getParent().setBackground(Color.WHITE);
    }

    private ODB_Cursos _cursos = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        TxCurso = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxCNPJ = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TxInstituicao = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ChConcluido = new javax.swing.JCheckBox();
        TxNomeCurso = new javax.swing.JTextField();
        TxCPFCurso = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        BtNovo = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtBuscarLista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DgCurso = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CURSOS");
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMAÇÕES ADICIONAIS"));
        jPanel3.setLayout(null);

        TxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCursoActionPerformed(evt);
            }
        });
        TxCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxCursoKeyReleased(evt);
            }
        });
        jPanel3.add(TxCurso);
        TxCurso.setBounds(10, 110, 190, 22);

        jLabel23.setText("CURSO");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(10, 90, 60, 16);

        TxCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCNPJActionPerformed(evt);
            }
        });
        TxCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxCNPJKeyPressed(evt);
            }
        });
        jPanel3.add(TxCNPJ);
        TxCNPJ.setBounds(210, 110, 140, 22);

        jLabel24.setText("CPF");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(10, 40, 60, 16);

        TxInstituicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxInstituicaoActionPerformed(evt);
            }
        });
        TxInstituicao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxInstituicaoKeyReleased(evt);
            }
        });
        jPanel3.add(TxInstituicao);
        TxInstituicao.setBounds(360, 110, 310, 22);

        jLabel25.setText("INSTITUIÇÃO");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(360, 90, 110, 16);

        ChConcluido.setBackground(new java.awt.Color(255, 255, 255));
        ChConcluido.setText("CONCLUIDO");
        jPanel3.add(ChConcluido);
        ChConcluido.setBounds(430, 60, 110, 20);

        TxNomeCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNomeCursoKeyReleased(evt);
            }
        });
        jPanel3.add(TxNomeCurso);
        TxNomeCurso.setBounds(170, 60, 250, 22);

        TxCPFCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCPFCursoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxCPFCursoKeyPressed(evt);
            }
        });
        jPanel3.add(TxCPFCurso);
        TxCPFCurso.setBounds(10, 60, 150, 22);

        jLabel42.setText("CNPJ");
        jPanel3.add(jLabel42);
        jLabel42.setBounds(210, 90, 60, 16);

        jLabel43.setText("NOME");
        jPanel3.add(jLabel43);
        jLabel43.setBounds(170, 40, 60, 16);

        BtNovo.setBackground(new java.awt.Color(255, 255, 255));
        BtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo.png"))); // NOI18N
        BtNovo.setToolTipText("NOVO");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });
        jPanel3.add(BtNovo);
        BtNovo.setBounds(680, 90, 50, 50);

        BtExcluir.setBackground(new java.awt.Color(255, 255, 255));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Excluir.png"))); // NOI18N
        BtExcluir.setToolTipText("EXCLUIR");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(BtExcluir);
        BtExcluir.setBounds(680, 20, 50, 50);

        BtBuscarLista.setBackground(new java.awt.Color(255, 255, 255));
        BtBuscarLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Listar.png"))); // NOI18N
        BtBuscarLista.setToolTipText("BUSCAR");
        jPanel3.add(BtBuscarLista);
        BtBuscarLista.setBounds(630, 20, 50, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 20, 740, 160);

        DgCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CURSO", "INSTITUICAO", "CNPJ", "CONCLUIDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(DgCurso);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 190, 740, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCursoActionPerformed

    private void TxCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCursoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxCurso.setText(TxCurso.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxCursoKeyReleased

    private void TxCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCNPJActionPerformed

    private void TxInstituicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxInstituicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxInstituicaoActionPerformed

    private void TxInstituicaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxInstituicaoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxInstituicao.setText(TxInstituicao.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxInstituicaoKeyReleased

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        try{

            this._cursos = new ODB_Cursos();
            this._cursos.setID(Selecionar.Consultar_IDDetetive(Criptografia.Cripto(TxCPFCurso.getText())));
            this._cursos.setCPF(TxCPFCurso.getText());
            this._cursos.setCurso(TxCurso.getText());
            this._cursos.setCNPJ(TxCNPJ.getText());
            this._cursos.setInstituicao(TxInstituicao.getText());
            this._cursos.setConcluido(ChConcluido.isSelected());
            
            Inserir.Criar_DetetiveCursos(_cursos);
            
            this._cursos = null;

            TxCPFCurso.setText("");
            TxNomeCurso.setText("");
            TxCurso.setText("");
            TxCNPJ.setText("");
            TxInstituicao.setText("");

        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,"A DATA DEVE ESTA NO FORMATO (dd/MM/yyyy), FAVOR VERIFIQUE","ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try
        {

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void TxCPFCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFCursoKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                
                String Retorno = Selecionar.Consultar_CPFDetetive(Criptografia.Cripto(TxCPFCurso.getText()));
                
                if(Retorno.equals("")){
                    throw new Exception("DETETIVE NÃO ENCONTRADO, FAVOR VERIFIQUE");
                }else{
                    TxNomeCurso.setText(Retorno);
                    TxCurso.requestFocus();
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxCPFCursoKeyPressed

    private void TxCPFCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFCursoKeyTyped
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxCPFCursoKeyTyped

    private void TxNomeCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeCursoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxNomeCurso.setText(TxNomeCurso.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxNomeCursoKeyReleased

    private void TxCNPJKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCNPJKeyPressed
        try{
            
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(TxCNPJ.getText().equals("")){
                    throw new Exception("POR FAVOR INFORME UM CNPJ");
                }else{
                    ODB_Validador valida = new ODB_Validador();
                    Boolean Retorno = valida.isCNPJ(TxCNPJ.getText());

                    if(Retorno.equals(true)){
                        TxInstituicao.requestFocus();
                    }else{
                        throw new Exception("CNPJ INVALIDO, FAVOR VERIFIQUE");
                    }
                }
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxCNPJKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscarLista;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovo;
    private javax.swing.JCheckBox ChConcluido;
    private javax.swing.JTable DgCurso;
    private javax.swing.JTextField TxCNPJ;
    private javax.swing.JTextField TxCPFCurso;
    private javax.swing.JTextField TxCurso;
    private javax.swing.JTextField TxInstituicao;
    private javax.swing.JTextField TxNomeCurso;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
