/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import Banco.Inserir;
import Banco.Selecionar;
import Classes.Criptografia;
import Classes.ODB_BuscaCEP;
import Classes.ODB_Cursos;
import Classes.ODB_Detetive;
import Classes.ODB_DetetiveComplemento;
import Classes.ODB_EstadoCivil;
import Classes.ODB_Grupo;
import Classes.ODB_Parameter;
import Classes.ODB_Sexo;
import Classes.ODB_TipoCadastro;
import Classes.ODB_UF;
import Classes.ODB_ValidaURL;
import Classes.ODB_Validador;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.GregorianCalendar;
import static javax.print.attribute.Size2DSyntax.MM;
/**
 *
 * @author Administrador
 */
public class FrmDetetive extends javax.swing.JFrame {

    /**
     * Creates new form FrmDetetive
     */
    public FrmDetetive() {
        initComponents();
        
        //IniciaLizarWebCam();
        
         CbUF.removeAllItems();
                
        ArrayList<ODB_UF> Listar_UF = Selecionar.Listar_Estados();

        if(Listar_UF != null){
            for(int i = 0; i < Listar_UF.size(); i++){
                CbUF.addItem(Listar_UF.get(i).getDescricao().toUpperCase());
            }
        }
        
         CbSexo.removeAllItems();
                
        ArrayList<ODB_Sexo> Listar_Sexo = Selecionar.Listar_Sexo();

        if(Listar_Sexo != null){
            for(int i = 0; i < Listar_Sexo.size(); i++){
                CbSexo.addItem(Listar_Sexo.get(i).getDescricao().toUpperCase());
            }
        }
        
         CbEstadoCivil.removeAllItems();
                
        ArrayList<ODB_EstadoCivil> Listar_EstadoCivil = Selecionar.Listar_EstadoCivil();

        if(Listar_EstadoCivil != null){
            for(int i = 0; i < Listar_EstadoCivil.size(); i++){
                CbEstadoCivil.addItem(Listar_EstadoCivil.get(i).getDescricao().toUpperCase());
            }
        }
        
         CbGrupo.removeAllItems();
                
        ArrayList<ODB_Grupo> Listar_grupo = Selecionar.Listar_Grupos();

        if(Listar_grupo != null){
            for(int i = 0; i < Listar_grupo.size(); i++){
                CbGrupo.addItem(Listar_grupo.get(i).getDescricao().toUpperCase());
            }
        }
        
         CbAssociado.removeAllItems();
                
        ArrayList<ODB_TipoCadastro> Listar_TipoCadastro = Selecionar.Listar_TipoCadastro();

        if(Listar_TipoCadastro != null){
            for(int i = 0; i < Listar_TipoCadastro.size(); i++){
                CbAssociado.addItem(Listar_TipoCadastro.get(i).getDescricao().toUpperCase());
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxRG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CbSexo = new javax.swing.JComboBox<>();
        TxNaturalidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxNascimento = new javax.swing.JTextField();
        CbUF = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TxTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxNomeMae = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxNomePai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CbEstadoCivil = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        TxRegistro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxValidade = new javax.swing.JTextField();
        CbAssociado = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TxZona = new javax.swing.JTextField();
        TxSessao = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        TxConjuge = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        TxEmail = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TxSite = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        ChAtivo = new javax.swing.JCheckBox();
        CbGrupo = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        ChAniversario = new javax.swing.JCheckBox();
        BtGerar = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        LbFoto = new javax.swing.JLabel();
        BtFoto = new javax.swing.JToggleButton();
        RdWebCam = new javax.swing.JRadioButton();
        RdImportar = new javax.swing.JRadioButton();
        BtBuscar = new javax.swing.JButton();
        BtNovo = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        TxCep = new javax.swing.JTextField();
        BtBuscarCep = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        TxEndereco = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxComplemento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxBairro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxUF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        TxCidade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TxDDD = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxTelefone = new javax.swing.JTextField();
        TxNumero = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        BtCurso = new javax.swing.JButton();
        BtPararCaptura = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        BtAnexo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO DE DETETIVES");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMAÇÕES"));
        jPanel2.setLayout(null);

        jLabel1.setText("NOME COMPLETO");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 30, 130, 16);

        TxNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNomeKeyReleased(evt);
            }
        });
        jPanel2.add(TxNome);
        TxNome.setBounds(20, 50, 240, 22);

        jLabel2.setText("CPF");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(270, 30, 90, 16);

        TxCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCPFKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxCPFKeyPressed(evt);
            }
        });
        jPanel2.add(TxCPF);
        TxCPF.setBounds(270, 50, 140, 22);

        jLabel3.setText("RG");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(420, 30, 80, 16);

        TxRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxRGKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxRGKeyPressed(evt);
            }
        });
        jPanel2.add(TxRG);
        TxRG.setBounds(420, 50, 110, 22);

        jLabel4.setText("SEXO");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 80, 50, 16);

        CbSexo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbSexoMousePressed(evt);
            }
        });
        jPanel2.add(CbSexo);
        CbSexo.setBounds(20, 100, 120, 22);

        TxNaturalidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNaturalidadeKeyReleased(evt);
            }
        });
        jPanel2.add(TxNaturalidade);
        TxNaturalidade.setBounds(270, 100, 140, 22);

        jLabel5.setText("NATURALIDADE");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(270, 80, 110, 16);

        jLabel6.setText("NASCIMENTO");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 80, 110, 16);

        TxNascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxNascimentoKeyPressed(evt);
            }
        });
        jPanel2.add(TxNascimento);
        TxNascimento.setBounds(150, 100, 110, 22);

        CbUF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbUFMousePressed(evt);
            }
        });
        jPanel2.add(CbUF);
        CbUF.setBounds(420, 100, 110, 22);

        jLabel7.setText("UF");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 80, 50, 16);

        TxTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxTituloKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxTituloKeyPressed(evt);
            }
        });
        jPanel2.add(TxTitulo);
        TxTitulo.setBounds(540, 50, 110, 22);

        jLabel8.setText("TITULO");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(540, 30, 110, 16);

        TxNomeMae.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxNomeMaeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNomeMaeKeyReleased(evt);
            }
        });
        jPanel2.add(TxNomeMae);
        TxNomeMae.setBounds(20, 150, 200, 22);

        jLabel9.setText("NOME DA MÃE");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 130, 110, 16);

        TxNomePai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNomePaiKeyReleased(evt);
            }
        });
        jPanel2.add(TxNomePai);
        TxNomePai.setBounds(230, 150, 170, 22);

        jLabel10.setText("NOME DO PAI");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(230, 130, 110, 16);

        CbEstadoCivil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbEstadoCivilMousePressed(evt);
            }
        });
        jPanel2.add(CbEstadoCivil);
        CbEstadoCivil.setBounds(540, 100, 110, 22);

        jLabel11.setText("ESTADO CIVIL");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 80, 120, 16);
        jPanel2.add(TxRegistro);
        TxRegistro.setBounds(410, 150, 90, 22);

        jLabel12.setText("REGISTRO ODB");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(410, 130, 110, 16);

        jLabel13.setText("VALIDADE");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(530, 130, 110, 16);

        TxValidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxValidadeKeyPressed(evt);
            }
        });
        jPanel2.add(TxValidade);
        TxValidade.setBounds(530, 150, 120, 22);

        CbAssociado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbAssociadoMousePressed(evt);
            }
        });
        jPanel2.add(CbAssociado);
        CbAssociado.setBounds(660, 150, 170, 22);

        jLabel26.setText("TIPO CADASTRO");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(660, 130, 110, 16);

        jLabel27.setText("ZONA");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(660, 30, 70, 16);

        TxZona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxZonaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxZonaKeyPressed(evt);
            }
        });
        jPanel2.add(TxZona);
        TxZona.setBounds(660, 50, 60, 22);

        TxSessao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxSessaoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxSessaoKeyPressed(evt);
            }
        });
        jPanel2.add(TxSessao);
        TxSessao.setBounds(730, 50, 60, 22);

        jLabel28.setText("SESSÃO");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(730, 30, 70, 16);

        TxConjuge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxConjugeKeyReleased(evt);
            }
        });
        jPanel2.add(TxConjuge);
        TxConjuge.setBounds(660, 100, 170, 22);

        jLabel29.setText("NOME DO CONJUGE");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(660, 80, 140, 16);

        TxEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxEmailKeyReleased(evt);
            }
        });
        jPanel2.add(TxEmail);
        TxEmail.setBounds(20, 200, 200, 22);

        jLabel30.setText("EMAIL");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(20, 180, 110, 16);

        TxSite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxSiteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxSiteKeyReleased(evt);
            }
        });
        jPanel2.add(TxSite);
        TxSite.setBounds(230, 200, 290, 22);

        jLabel31.setText("SITE");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(230, 180, 110, 16);

        ChAtivo.setBackground(new java.awt.Color(255, 255, 255));
        ChAtivo.setText("ATIVO");
        jPanel2.add(ChAtivo);
        ChAtivo.setBounds(710, 180, 110, 20);

        CbGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CbGrupoMousePressed(evt);
            }
        });
        jPanel2.add(CbGrupo);
        CbGrupo.setBounds(530, 200, 170, 22);

        jLabel32.setText("GRUPO");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(530, 180, 110, 16);

        ChAniversario.setBackground(new java.awt.Color(255, 255, 255));
        ChAniversario.setText("ANIVERSÁRIO");
        ChAniversario.setToolTipText("ALERTAR ANIVERSÁRIO");
        jPanel2.add(ChAniversario);
        ChAniversario.setBounds(710, 200, 130, 20);

        BtGerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo.png"))); // NOI18N
        BtGerar.setToolTipText("GERAR NÚMERO");
        BtGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGerarActionPerformed(evt);
            }
        });
        jPanel2.add(BtGerar);
        BtGerar.setBounds(500, 150, 20, 20);

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setForeground(new java.awt.Color(255, 51, 51));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("*");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(260, 50, 10, 20);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setForeground(new java.awt.Color(255, 51, 51));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("*");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(410, 50, 10, 20);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setForeground(new java.awt.Color(255, 51, 51));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("*");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(520, 150, 10, 20);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("*");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(650, 150, 10, 20);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setForeground(new java.awt.Color(255, 51, 51));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("*");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(260, 100, 10, 20);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setForeground(new java.awt.Color(255, 51, 51));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("*");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(220, 200, 10, 20);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setForeground(new java.awt.Color(255, 51, 51));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("*");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(830, 150, 10, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 10, 850, 230);

        LbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sem-foto.jpg"))); // NOI18N
        LbFoto.setOpaque(true);
        getContentPane().add(LbFoto);
        LbFoto.setBounds(560, 240, 310, 200);

        BtFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INVESTIGACAO1.png"))); // NOI18N
        BtFoto.setText("FOTO");
        BtFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFotoActionPerformed(evt);
            }
        });
        getContentPane().add(BtFoto);
        BtFoto.setBounds(600, 450, 110, 30);

        RdWebCam.setBackground(new java.awt.Color(255, 255, 255));
        RdWebCam.setText("WEBCAM");
        getContentPane().add(RdWebCam);
        RdWebCam.setBounds(450, 460, 100, 20);

        RdImportar.setBackground(new java.awt.Color(255, 255, 255));
        RdImportar.setText("IMPORTAR");
        getContentPane().add(RdImportar);
        RdImportar.setBounds(450, 440, 100, 20);

        BtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        BtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGINS.png"))); // NOI18N
        BtBuscar.setToolTipText("FECHAR");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BtBuscar);
        BtBuscar.setBounds(320, 430, 50, 50);

        BtNovo.setBackground(new java.awt.Color(255, 255, 255));
        BtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo.png"))); // NOI18N
        BtNovo.setToolTipText("NOVO");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });
        getContentPane().add(BtNovo);
        BtNovo.setBounds(20, 430, 50, 50);

        BtSalvar.setBackground(new java.awt.Color(255, 255, 255));
        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salvar.png"))); // NOI18N
        BtSalvar.setToolTipText("SALVAR");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalvar);
        BtSalvar.setBounds(70, 430, 50, 50);

        BtExcluir.setBackground(new java.awt.Color(255, 255, 255));
        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Excluir.png"))); // NOI18N
        BtExcluir.setToolTipText("EXCLUIR");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(BtExcluir);
        BtExcluir.setBounds(120, 430, 50, 50);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("OUTRAS INFORMAÇÕES"));
        jPanel1.setLayout(null);

        jLabel14.setText("CEP");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 40, 71, 16);

        TxCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCepKeyTyped(evt);
            }
        });
        jPanel1.add(TxCep);
        TxCep.setBounds(20, 60, 95, 22);

        BtBuscarCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        BtBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarCepActionPerformed(evt);
            }
        });
        jPanel1.add(BtBuscarCep);
        BtBuscarCep.setBounds(120, 60, 20, 20);

        jLabel15.setText("ENDEREÇO");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 40, 261, 16);

        TxEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxEnderecoKeyReleased(evt);
            }
        });
        jPanel1.add(TxEndereco);
        TxEndereco.setBounds(150, 60, 380, 22);

        jLabel16.setText("COMPLEMENTO");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 90, 141, 16);

        TxComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxComplementoActionPerformed(evt);
            }
        });
        TxComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxComplementoKeyReleased(evt);
            }
        });
        jPanel1.add(TxComplemento);
        TxComplemento.setBounds(20, 110, 210, 22);

        jLabel17.setText("BAIRRO");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(340, 90, 95, 16);

        TxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBairroActionPerformed(evt);
            }
        });
        jPanel1.add(TxBairro);
        TxBairro.setBounds(340, 110, 188, 22);

        jLabel18.setText("UF");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 140, 60, 16);

        TxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxUFActionPerformed(evt);
            }
        });
        jPanel1.add(TxUF);
        TxUF.setBounds(20, 160, 90, 22);

        jLabel19.setText("CIDADE");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(120, 140, 86, 16);
        jPanel1.add(TxCidade);
        TxCidade.setBounds(120, 160, 210, 22);

        jLabel20.setText("DDD");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(340, 140, 56, 16);

        TxDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDDDActionPerformed(evt);
            }
        });
        TxDDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxDDDKeyTyped(evt);
            }
        });
        jPanel1.add(TxDDD);
        TxDDD.setBounds(340, 160, 55, 22);

        jLabel21.setText("TELEFONE");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(400, 140, 77, 16);

        TxTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxTelefoneKeyTyped(evt);
            }
        });
        jPanel1.add(TxTelefone);
        TxTelefone.setBounds(400, 160, 130, 22);

        TxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNumeroActionPerformed(evt);
            }
        });
        TxNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxNumeroKeyTyped(evt);
            }
        });
        jPanel1.add(TxNumero);
        TxNumero.setBounds(240, 110, 90, 22);

        jLabel22.setText("NÚMERO");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(240, 90, 95, 16);

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setForeground(new java.awt.Color(255, 51, 51));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("*");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(330, 110, 10, 20);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setForeground(new java.awt.Color(255, 51, 51));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("*");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(140, 60, 10, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 240, 540, 190);

        BtCurso.setBackground(new java.awt.Color(255, 255, 255));
        BtCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/curso.png"))); // NOI18N
        BtCurso.setToolTipText("CURSO");
        BtCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCursoActionPerformed(evt);
            }
        });
        getContentPane().add(BtCurso);
        BtCurso.setBounds(170, 430, 50, 50);

        BtPararCaptura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INVESTIGACAO1.png"))); // NOI18N
        BtPararCaptura.setText("PARAR");
        BtPararCaptura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtPararCaptura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPararCapturaActionPerformed(evt);
            }
        });
        getContentPane().add(BtPararCaptura);
        BtPararCaptura.setBounds(730, 450, 110, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer.png"))); // NOI18N
        jButton1.setToolTipText("IMPRIMIR");
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 430, 50, 50);

        BtAnexo.setBackground(new java.awt.Color(255, 255, 255));
        BtAnexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arquivo-anexo.png"))); // NOI18N
        BtAnexo.setToolTipText("ANEXAR ARQUIVOS");
        BtAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAnexoActionPerformed(evt);
            }
        });
        getContentPane().add(BtAnexo);
        BtAnexo.setBounds(270, 430, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ODB_Detetive _detetive = null;
    
    private ODB_DetetiveComplemento _complemento = null;
    
    private void IniciaLizarWebCam(){
        try{
            ODB_Parameter._dimensaoDefault = WebcamResolution.VGA.getSize();
            ODB_Parameter._Webcam = Webcam.getDefault();
            ODB_Parameter._Webcam.setViewSize(ODB_Parameter._dimensaoDefault);

            for(Dimension dimensao : ODB_Parameter._Webcam.getViewSizes()){
                System.out.println("Largura: " + dimensao.getWidth() + "Largura: " + dimensao.getHeight());
            }
        }catch(WebcamException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO", JOptionPane.PLAIN_MESSAGE);
        }
    }
    
    private void Inicializa_Captura(){
        new Thread(){
            
            @Override
            public void run(){
                while(true){
                    try{
                        Image _foto = ODB_Parameter._Webcam.getImage();
                        ImageIcon _iconn = new ImageIcon(_foto);
                        _iconn.setImage(_iconn.getImage().getScaledInstance(LbFoto.getWidth(), LbFoto.getHeight(), 100));
                        LbFoto.setIcon(_iconn);
                        Thread.sleep(50);
                        
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO", JOptionPane.PLAIN_MESSAGE);
                    }
                }
            }
        }.start();
    }
    private void BtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFotoActionPerformed
        // TODO add your handling code here:
        try
        {
            if(RdImportar.isSelected()){
                JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);

                File file = chooser.getSelectedFile();
                ODB_Parameter.CaminhoFoto = file.getAbsolutePath();

                ImageIcon icone1 = new ImageIcon(ODB_Parameter.CaminhoFoto);
                Image img = icone1.getImage().getScaledInstance(LbFoto.getWidth(), LbFoto.getHeight(), Image.SCALE_DEFAULT);
                LbFoto.setIcon(new ImageIcon(img));
            
            }else if (RdWebCam.isSelected()){
                
                new Thread(){
                    public void run(){
                        LbFoto.setText("Inicializando leitura...");
                        
                        ODB_Parameter._Webcam.open();
                        
                        LbFoto.setText("");
                        
                        Inicializa_Captura();
                    }
                    
                }.start();
                
            }else{
                throw new Exception("FAVOR SELECIONE UMA DAS OPÇÕES AO LADO");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO", JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_BtFotoActionPerformed

    private void TxCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCepKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxCepKeyTyped

    private void BtBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarCepActionPerformed
        // TODO add your handling code here:
        try{

            if(!TxCep.getText().equals("")){
                ODB_BuscaCEP busca = new ODB_BuscaCEP();
                busca.BuscaCEP(TxCep.getText());

                TxCep.setText(ODB_BuscaCEP._Cep_.replace("-", ""));
                TxEndereco.setText(ODB_BuscaCEP.Endereco.toUpperCase());
                TxBairro.setText(ODB_BuscaCEP.Bairro.toUpperCase());
                TxUF.setText(ODB_BuscaCEP.UF.toUpperCase());
                TxCidade.setText(ODB_BuscaCEP.Cidade.toUpperCase());
                TxDDD.setText(ODB_BuscaCEP.DDD);

            }else{

                throw new Exception("FAVOR INFORME UM CEP VÁLIDO");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO de conexão", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BtBuscarCepActionPerformed

    private void TxEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxEnderecoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxEndereco.setText(TxEndereco.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxEnderecoKeyReleased

    private void TxComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxComplementoActionPerformed

    private void TxComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxComplementoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxComplemento.setText(TxComplemento.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxComplementoKeyReleased

    private void TxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBairroActionPerformed

    private void TxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxUFActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_TxUFActionPerformed

    private void TxDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDDDActionPerformed

    private void TxDDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxDDDKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxDDDKeyTyped

    private void TxTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxTelefoneKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxTelefoneKeyTyped

    private void TxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNumeroActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void CbUFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbUFMousePressed
        try{
            ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
            
            if(CbUF.getItemCount() == 0){
                CbUF.removeAllItems();
                
                ArrayList<ODB_UF> Listar_UF = Selecionar.Listar_Estados();

                if(Listar_UF != null){
                    for(int i = 0; i < Listar_UF.size(); i++){
                        CbUF.addItem(Listar_UF.get(i).getDescricao().toUpperCase());
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_CbUFMousePressed

    private void TxCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(TxCPF.getText().isEmpty()){
                    
                    throw new Exception("CAMPO CPF/CNPJ NÃO PODE SER NULO, FAVOR VERIFIQUE");
                    
                }else{
                    
                    ODB_Validador valida = new ODB_Validador();
                    
                    if(TxCPF.getText().trim().length() == 11)
                    {
                        Boolean RetornoCPF = valida.isCPF(TxCPF.getText());

                        if(RetornoCPF.equals(false)){

                            throw new Exception("CPF INVÁLIDO, FAVOR VERIFIQUE");
                        }
                        else{

                            TxRG.requestFocus();
                        }
                    }else if (TxCPF.getText().trim().length() == 14){
                        
                        Boolean RetornoCNPJ = valida.isCNPJ(TxCPF.getText());
                        
                        if(RetornoCNPJ.equals(false)){
                            throw new Exception("CNPJ INVÁLIDO, FAVOR VERIFIQUE");
                        }else{
                            TxRG.requestFocus();
                        }
                    }else{
                        throw new Exception("CNPJ OU CNPJ INVÁLIDO");
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TxCPFKeyPressed

    private void CbSexoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbSexoMousePressed
        try{
            ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
            
            if(CbSexo.getItemCount() == 0){
                CbSexo.removeAllItems();
                
                ArrayList<ODB_Sexo> Listar_Sexo = Selecionar.Listar_Sexo();

                if(Listar_Sexo != null){
                    for(int i = 0; i < Listar_Sexo.size(); i++){
                        CbSexo.addItem(Listar_Sexo.get(i).getDescricao().toUpperCase());
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_CbSexoMousePressed

    private void CbEstadoCivilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbEstadoCivilMousePressed
        try{
            ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
            
            if(CbEstadoCivil.getItemCount() == 0){
                CbEstadoCivil.removeAllItems();
                
                ArrayList<ODB_EstadoCivil> Listar_EstadoCivil = Selecionar.Listar_EstadoCivil();

                if(Listar_EstadoCivil != null){
                    for(int i = 0; i < Listar_EstadoCivil.size(); i++){
                        CbEstadoCivil.addItem(Listar_EstadoCivil.get(i).getDescricao().toUpperCase());
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_CbEstadoCivilMousePressed

    private void CbGrupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbGrupoMousePressed
        try{
            ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
            
            if(CbGrupo.getItemCount() == 0){
                CbGrupo.removeAllItems();
                
                ArrayList<ODB_Grupo> Listar_grupo = Selecionar.Listar_Grupos();

                if(Listar_grupo != null){
                    for(int i = 0; i < Listar_grupo.size(); i++){
                        CbGrupo.addItem(Listar_grupo.get(i).getDescricao().toUpperCase());
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_CbGrupoMousePressed

    private void CbAssociadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbAssociadoMousePressed
        try{
            ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
            
            if(CbAssociado.getItemCount() == 0){
                CbAssociado.removeAllItems();
                
                ArrayList<ODB_TipoCadastro> Listar_TipoCadastro = Selecionar.Listar_TipoCadastro();

                if(Listar_TipoCadastro != null){
                    for(int i = 0; i < Listar_TipoCadastro.size(); i++){
                        CbAssociado.addItem(Listar_TipoCadastro.get(i).getDescricao().toUpperCase());
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_CbAssociadoMousePressed

    private void BtGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGerarActionPerformed
        try{
            
            Random numero = new Random();
            TxRegistro.setText(String.valueOf(numero.nextInt(999999)));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtGerarActionPerformed

    private void TxValidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxValidadeKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
                Date _data;
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                format.setLenient(false);
                _data = format.parse(TxValidade.getText());

            }
        }catch(ParseException  ex){
            JOptionPane.showMessageDialog(null,"A DATA DEVE ESTA NO FORMATO (dd/MM/yyyy), FAVOR VERIFIQUE","ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxValidadeKeyPressed

    private void TxSiteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxSiteKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                Boolean retorno = ODB_ValidaURL.ValidarURL(TxSite.getText());
                
                if(retorno.equals(false)){
                    throw new Exception("SITE INVÁLIDO");
                }else{
                    TxCep.requestFocus();
                }
            }
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxSiteKeyPressed

    private void TxNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                TxCPF.requestFocus();
            }
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxNomeKeyPressed

    private void TxRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxRGKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                TxTitulo.requestFocus();
            }
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxRGKeyPressed

    private void TxTituloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxTituloKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                TxZona.requestFocus();
            }
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxTituloKeyPressed

    private void TxZonaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxZonaKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                TxSessao.requestFocus();
            }
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxZonaKeyPressed

    private void TxSessaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxSessaoKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                TxNascimento.requestFocus();
            }
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxSessaoKeyPressed

    private void TxNascimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNascimentoKeyPressed
          try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                ODB_Parameter.icon = new ImageIcon(System.getProperty("user.dir") + "\\Error.png");
                Date _data;
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                format.setLenient(false);
                _data = format.parse(TxNascimento.getText());

                TxNaturalidade.requestFocus();
            }
        }catch(ParseException  ex){
            JOptionPane.showMessageDialog(null,"A DATA DEVE ESTA NO FORMATO (dd/MM/yyyy), FAVOR VERIFIQUE","ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_TxNascimentoKeyPressed

    private void TxCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxCPFKeyTyped

    private void TxRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxRGKeyTyped
        // TODO add your handling code here:
              int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxRGKeyTyped

    private void TxTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxTituloKeyTyped
        // TODO add your handling code here:
              int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxTituloKeyTyped

    private void TxZonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxZonaKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxZonaKeyTyped

    private void TxSessaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxSessaoKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxSessaoKeyTyped

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        try{
            
            this._detetive = null;
            this._complemento = null;
            
            TxNome.setText("");
            TxCPF.setText("");
            TxRG.setText("");
            TxTitulo.setText("");
            TxZona.setText("0");
            TxSessao.setText("0");
            TxNascimento.setText("");
            TxNaturalidade.setText("");
            TxConjuge.setText("");
            TxNomeMae.setText("");
            TxNomePai.setText("");
            TxRegistro.setText("");
            TxValidade.setText("");
            TxEmail.setText("");
            TxSite.setText("");
            TxCep.setText("0");
            TxEndereco.setText("");
            TxComplemento.setText("");
            TxNumero.setText("0");
            TxBairro.setText("");
            TxUF.setText("");
            TxCidade.setText("");
            TxDDD.setText("");
            TxTelefone.setText("");
            ChAtivo.setSelected(false);
            ChAniversario.setSelected(false);
            
            
        }catch(Exception  ex){
            JOptionPane.showMessageDialog(null,"A DATA DEVE ESTA NO FORMATO (dd/MM/yyyy), FAVOR VERIFIQUE","ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try{
            
                Date data = new Date();
                Calendar Nascimento = Calendar.getInstance();
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                Nascimento.setTime(format.parse(TxNascimento.getText()));
                
                Calendar Validade = Calendar.getInstance();
                Validade.setTime(format.parse(TxValidade.getText()));
                
                Calendar DataAtual = new GregorianCalendar();
                
                if(TxNome.getText().equals("") && TxCPF.getText().equals("") && TxRegistro.getText().equals("")&& TxTelefone.getText().equals("")){
                    throw new Exception("EXISTEM CAMPOS OBRIGATÓRIOS A SERREM PREENCHIDOS");
                }else{
                    if(_detetive == null){
                        _detetive = new ODB_Detetive();
                        _detetive.setNome(TxNome.getText());
                        _detetive.setCPF(Criptografia.Cripto(TxCPF.getText()));
                        _detetive.setRG(Criptografia.Cripto(TxRG.getText()));
                        _detetive.setTitulo(Criptografia.Cripto(TxTitulo.getText()));
                        if(TxZona.getText().equals("")){
                            _detetive.setZona(0);
                        }else{
                            _detetive.setZona(Integer.parseInt(TxZona.getText()));}

                        if(TxSessao.getText().equals("")){
                            _detetive.setSessao(0);
                        }else{
                        _detetive.setSessao(Integer.parseInt(TxSessao.getText()));}

                        _detetive.setSexo(Selecionar.Consultar_IDSexo(CbSexo.getSelectedItem().toString()));
                        _detetive.setNascimento(Nascimento);
                        _detetive.setNaturalidade(TxNaturalidade.getText());
                        _detetive.setUF(CbUF.getSelectedItem().toString());
                        _detetive.setEstadoCivil(Selecionar.Consultar_IDEstadoCivil(CbEstadoCivil.getSelectedItem().toString()));
                        _detetive.setConjuge(TxConjuge.getName());
                        _detetive.setNomeMae(TxNomeMae.getText());
                        _detetive.setNomePai(TxNomePai.getText());
                        _detetive.setRegistroODB(Integer.parseInt(TxRegistro.getText()));
                        _detetive.setValidade(Validade);
                        _detetive.setTipoCadastro(Selecionar.Consultar_IDTipoCadastro(CbAssociado.getSelectedItem().toString()));
                        _detetive.setEmail(TxEmail.getText());
                        _detetive.setSite(TxSite.getText());
                        _detetive.setGrupo(Selecionar.Consultar_IDGrupo(CbGrupo.getSelectedItem().toString()));
                        _detetive.setAtivo(ChAtivo.isSelected());
                        _detetive.setAvisarAniversario(ChAniversario.isSelected());
                        _detetive.setDataCadastro(DataAtual);
                        _detetive.setFoto(ODB_Parameter.CaminhoFoto);
                        
                        Inserir.Criar_Detetives(_detetive);

                        Thread.sleep(50);
                        
                        _complemento = new ODB_DetetiveComplemento();

                        _complemento.setCodigoDetetive(Selecionar.Consultar_IDDetetive(Criptografia.Cripto(TxCPF.getText())));
                        _complemento.setCep(Integer.parseInt(TxCep.getText()));
                        _complemento.setEndereco(TxEndereco.getText());
                        _complemento.setComplemento(TxComplemento.getText());

                        if(TxNumero.getText().equals("")){
                            _complemento.setNumero(0);
                        }else{
                        _complemento.setNumero(Integer.parseInt(TxNumero.getText()));}
                        _complemento.setBairro(TxBairro.getText());
                        _complemento.setUFEndereco(TxUF.getText());
                        _complemento.setCidade(TxCidade.getText());
                        if(TxDDD.getText().equals("")){
                            _complemento.setDDD(0);
                        }else{
                        _complemento.setDDD(Integer.parseInt(TxDDD.getText()));}
                        _complemento.setTelefone(TxTelefone.getText());

                        Inserir.Criar_DetetivesComplemento(_complemento);
                
                    }else{//Atualiza Cadastro

                        _detetive.setNome(TxNome.getText());
                        _detetive.setCPF(Criptografia.Cripto(TxCPF.getText()));
                        _detetive.setRG(Criptografia.Cripto(TxRG.getText()));
                        _detetive.setTitulo(Criptografia.Cripto(TxTitulo.getText()));
                        if(TxZona.getText().equals("")){
                            _detetive.setZona(0);
                        }else{
                            _detetive.setZona(Integer.parseInt(TxZona.getText()));}

                        if(TxSessao.getText().equals("")){
                            _detetive.setSessao(0);
                        }else{
                        _detetive.setSessao(Integer.parseInt(TxSessao.getText()));}

                        _detetive.setSexo(Selecionar.Consultar_IDSexo(CbSexo.getSelectedItem().toString()));
                        _detetive.setNascimento(Nascimento);
                        _detetive.setNaturalidade(TxNaturalidade.getText());
                        _detetive.setUF(CbUF.getSelectedItem().toString());
                        _detetive.setEstadoCivil(Selecionar.Consultar_IDEstadoCivil(CbEstadoCivil.getSelectedItem().toString()));
                        _detetive.setConjuge(TxConjuge.getName());
                        _detetive.setNomeMae(TxNomeMae.getText());
                        _detetive.setNomePai(TxNomePai.getText());
                        _detetive.setRegistroODB(Integer.parseInt(TxRegistro.getText()));
                        _detetive.setValidade(Validade);
                        _detetive.setTipoCadastro(Selecionar.Consultar_IDTipoCadastro(CbAssociado.getSelectedItem().toString()));
                        _detetive.setEmail(TxEmail.getText());
                        _detetive.setSite(TxSite.getText());
                        _detetive.setGrupo(Selecionar.Consultar_IDGrupo(CbGrupo.getSelectedItem().toString()));
                        _detetive.setAtivo(ChAtivo.isSelected());
                        _detetive.setAvisarAniversario(ChAniversario.isSelected());
                        _detetive.setDataCadastro(DataAtual);
                        _detetive.setFoto(ODB_Parameter.CaminhoFoto);

                        _complemento.setCep(Integer.parseInt(TxCep.getText()));
                        _complemento.setEndereco(TxEndereco.getText());
                        _complemento.setComplemento(TxComplemento.getText());
                        _complemento.setNumero(Integer.parseInt(TxNumero.getText()));
                        _complemento.setBairro(TxBairro.getText());
                        _complemento.setUFEndereco(TxUF.getText());
                        _complemento.setCidade(TxCidade.getText());
                        _complemento.setDDD(Integer.parseInt(TxDDD.getText()));
                        _complemento.setTelefone(TxTelefone.getText());

                        }
                 }
                
        }catch(Exception  ex){
            _detetive = null;
            _complemento = null;
            
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtPararCapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPararCapturaActionPerformed
        try{
            ODB_Parameter._Webcam.close();
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtPararCapturaActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try
        {
             
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO", JOptionPane.INFORMATION_MESSAGE, ODB_Parameter.icon);
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void TxEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxEmailKeyPressed

    private void TxNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxNome.setText(TxNome.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxNomeKeyReleased

    private void TxNaturalidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNaturalidadeKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxNaturalidade.setText(TxNaturalidade.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxNaturalidadeKeyReleased

    private void TxConjugeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxConjugeKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxConjuge.setText(TxConjuge.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxConjugeKeyReleased

    private void TxNomeMaeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeMaeKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxNomeMae.setText(TxNomeMae.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxNomeMaeKeyReleased

    private void TxNomePaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomePaiKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxNomePai.setText(TxNomePai.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxNomePaiKeyReleased

    private void TxEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxEmailKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxEmail.setText(TxEmail.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxEmailKeyReleased

    private void TxSiteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxSiteKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxSite.setText(TxSite.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxSiteKeyReleased

    private void BtCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCursoActionPerformed
         String curDir = System.getProperty("user.dir") + "\\odb.fw.png";
        
        FrmCurso frm = new FrmCurso();
        frm.setSize(770, 460);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.setIconImage(Toolkit.getDefaultToolkit().getImage(curDir));
        frm.show();
    }//GEN-LAST:event_BtCursoActionPerformed

    private void BtAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAnexoActionPerformed
        String curDir = System.getProperty("user.dir") + "\\odb.fw.png";
        
        FrmAnexo frm = new FrmAnexo();
        frm.setSize(650, 415);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.setIconImage(Toolkit.getDefaultToolkit().getImage(curDir));
        frm.show();
    }//GEN-LAST:event_BtAnexoActionPerformed

    private void TxNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNumeroKeyTyped
                // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxNumeroKeyTyped

    private void TxNomeMaeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeMaeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TxNomePai.requestFocus();
        }
    }//GEN-LAST:event_TxNomeMaeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDetetive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDetetive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDetetive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDetetive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDetetive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAnexo;
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtBuscarCep;
    private javax.swing.JButton BtCurso;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JToggleButton BtFoto;
    private javax.swing.JButton BtGerar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JToggleButton BtPararCaptura;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox<String> CbAssociado;
    private javax.swing.JComboBox<String> CbEstadoCivil;
    private javax.swing.JComboBox<String> CbGrupo;
    private javax.swing.JComboBox<String> CbSexo;
    private javax.swing.JComboBox<String> CbUF;
    private javax.swing.JCheckBox ChAniversario;
    private javax.swing.JCheckBox ChAtivo;
    private javax.swing.JLabel LbFoto;
    private javax.swing.JRadioButton RdImportar;
    private javax.swing.JRadioButton RdWebCam;
    private javax.swing.JTextField TxBairro;
    private javax.swing.JTextField TxCPF;
    private javax.swing.JTextField TxCep;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JTextField TxComplemento;
    private javax.swing.JTextField TxConjuge;
    private javax.swing.JTextField TxDDD;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JTextField TxEndereco;
    private javax.swing.JTextField TxNascimento;
    private javax.swing.JTextField TxNaturalidade;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxNomeMae;
    private javax.swing.JTextField TxNomePai;
    private javax.swing.JTextField TxNumero;
    private javax.swing.JTextField TxRG;
    private javax.swing.JTextField TxRegistro;
    private javax.swing.JTextField TxSessao;
    private javax.swing.JTextField TxSite;
    private javax.swing.JTextField TxTelefone;
    private javax.swing.JTextField TxTitulo;
    private javax.swing.JTextField TxUF;
    private javax.swing.JTextField TxValidade;
    private javax.swing.JTextField TxZona;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
