/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;
import Classes.ODB_BuscaCEP;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Administrador
 */
public class FrmEventos extends javax.swing.JFrame {

    /**
     * Creates new form FrmEventos
     */
    public FrmEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxCep = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TxEndereco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxComplemento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxBairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxUF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxCidade = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxDDD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TxTelefone = new javax.swing.JTextField();
        TxNumero = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO EVENTO");
        getContentPane().setLayout(null);

        jLabel1.setText("EVENTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 100, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 60, 650, 22);

        jLabel2.setText("COORDENADOR DO EVENTO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 200, 16);

        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(20, 110, 310, 22);

        jLabel3.setText("VALOR INSCRIÇÃO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 90, 130, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(340, 110, 110, 22);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(200, 160, 120, 22);
        getContentPane().add(jLocaleChooser1);
        jLocaleChooser1.setBounds(20, 160, 170, 22);

        jLabel4.setText("DATA INICIO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 90, 90, 16);
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(570, 110, 102, 22);

        jLabel5.setText("DATA FINAL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 90, 90, 16);

        jLabel6.setText("PAÍS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 140, 60, 16);

        jLabel7.setText("INICIO INSCRIÇÕES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 140, 120, 16);
        getContentPane().add(jDateChooser3);
        jDateChooser3.setBounds(460, 110, 102, 22);

        jLabel8.setText("FIM INSCRIÇÕES");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 140, 120, 16);
        getContentPane().add(jDateChooser4);
        jDateChooser4.setBounds(330, 160, 120, 22);

        jLabel9.setText("DIA VENCIMENTO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(460, 140, 110, 16);
        getContentPane().add(jSpinField1);
        jSpinField1.setBounds(460, 160, 110, 22);

        jLabel10.setText("DURAÇÃO ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(580, 140, 90, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(580, 160, 100, 22);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("OUTRAS INFORMAÇÕES"));
        jPanel1.setLayout(null);

        jLabel11.setText("CEP");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(17, 29, 71, 16);

        TxCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCepKeyTyped(evt);
            }
        });
        jPanel1.add(TxCep);
        TxCep.setBounds(17, 51, 95, 22);

        BtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtBuscar);
        BtBuscar.setBounds(118, 51, 20, 20);

        jLabel12.setText("ENDEREÇO");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(152, 29, 261, 16);

        TxEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxEnderecoKeyReleased(evt);
            }
        });
        jPanel1.add(TxEndereco);
        TxEndereco.setBounds(152, 51, 261, 22);

        jLabel13.setText("COMPLEMENTO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 30, 141, 16);

        TxComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxComplementoActionPerformed(evt);
            }
        });
        TxComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxComplementoKeyReleased(evt);
            }
        });
        jPanel1.add(TxComplemento);
        TxComplemento.setBounds(420, 50, 210, 22);

        jLabel14.setText("BAIRRO");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(124, 101, 95, 16);

        TxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBairroActionPerformed(evt);
            }
        });
        jPanel1.add(TxBairro);
        TxBairro.setBounds(120, 120, 188, 22);

        jLabel15.setText("UF");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(320, 100, 60, 16);

        TxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxUFActionPerformed(evt);
            }
        });
        jPanel1.add(TxUF);
        TxUF.setBounds(320, 120, 90, 22);

        jLabel16.setText("CIDADE");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(420, 100, 86, 16);
        jPanel1.add(TxCidade);
        TxCidade.setBounds(420, 120, 208, 22);

        jLabel17.setText("DDD");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(17, 167, 56, 16);

        TxDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDDDActionPerformed(evt);
            }
        });
        TxDDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxDDDKeyTyped(evt);
            }
        });
        jPanel1.add(TxDDD);
        TxDDD.setBounds(17, 189, 55, 22);

        jLabel18.setText("TELEFONE");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(79, 167, 77, 16);

        TxTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxTelefoneKeyTyped(evt);
            }
        });
        jPanel1.add(TxTelefone);
        TxTelefone.setBounds(78, 189, 111, 22);

        TxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(TxNumero);
        TxNumero.setBounds(20, 120, 90, 22);

        jLabel19.setText("NÚMERO");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(17, 101, 95, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 200, 680, 240);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CALENDÁRIO"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 450, 680, 210);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Novo.png"))); // NOI18N
        jButton1.setToolTipText("NOVO");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salvar.png"))); // NOI18N
        jButton2.setToolTipText("SALVAR");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGINS.png"))); // NOI18N
        jButton3.setToolTipText("FECHAR");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 700, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCepKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxCepKeyTyped

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        // TODO add your handling code here:

        try{

            if(!TxCep.getText().equals("")){
                ODB_BuscaCEP busca = new ODB_BuscaCEP();
                busca.BuscaCEP(TxCep.getText());

                TxCep.setText(ODB_BuscaCEP._Cep_.replace("-", ""));
                TxEndereco.setText(ODB_BuscaCEP.Endereco.toUpperCase());
                TxBairro.setText(ODB_BuscaCEP.Bairro.toUpperCase());
                TxUF.setText(ODB_BuscaCEP.UF.toUpperCase());
                TxCidade.setText(ODB_BuscaCEP.Cidade.toUpperCase());
                TxDDD.setText(ODB_BuscaCEP.DDD);

            }else{

                throw new Exception("FAVOR INFORME UM CEP VÁLIDO");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO de conexão", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BtBuscarActionPerformed

    private void TxEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxEnderecoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxEndereco.setText(TxEndereco.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxEnderecoKeyReleased

    private void TxComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxComplementoActionPerformed

    private void TxComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxComplementoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
            TxComplemento.setText(TxComplemento.getText().toUpperCase());
        }
    }//GEN-LAST:event_TxComplementoKeyReleased

    private void TxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBairroActionPerformed

    private void TxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxUFActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_TxUFActionPerformed

    private void TxDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDDDActionPerformed

    private void TxDDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxDDDKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxDDDKeyTyped

    private void TxTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxTelefoneKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();

        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){

            evt.consume() ;

        }
    }//GEN-LAST:event_TxTelefoneKeyTyped

    private void TxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JTextField TxBairro;
    private javax.swing.JTextField TxCep;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JTextField TxComplemento;
    private javax.swing.JTextField TxDDD;
    private javax.swing.JTextField TxEndereco;
    private javax.swing.JTextField TxNumero;
    private javax.swing.JTextField TxTelefone;
    private javax.swing.JTextField TxUF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
