/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import Banco.Inserir;
import Classes.Criptografia;
import Classes.ODB_BuscaCEP;
import Classes.ODB_Host;
import Classes.ODB_Usuarios;
import Classes.ODB_Validador;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author detetive
 */
public class FrmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        
        /*ArrayList<ODB_ESTADO> _ListarUF = Selecionar.Listar_Estados();
        
        CbEntidade.removeAllItems();
        
        for(int i =0; i < _ListarUF.size(); i++){
            
            CbEntidade.addItem(_ListarUF.get(i).Nome);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxCep = new javax.swing.JTextField();
        BtBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxEndereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxComplemento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxUF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxCidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxDDD = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxTelefone = new javax.swing.JTextField();
        TxNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BtSalvar = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxRG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CbEntidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TxUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        TxEmail = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("OUTRAS INFORMAÇÕES"));
        jPanel1.setLayout(null);

        jLabel8.setText("CEP");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(17, 29, 71, 16);

        TxCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCepKeyTyped(evt);
            }
        });
        jPanel1.add(TxCep);
        TxCep.setBounds(17, 51, 95, 22);

        BtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtBuscar);
        BtBuscar.setBounds(118, 51, 20, 20);

        jLabel9.setText("ENDEREÇO");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(152, 29, 261, 16);

        TxEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxEnderecoKeyReleased(evt);
            }
        });
        jPanel1.add(TxEndereco);
        TxEndereco.setBounds(152, 51, 261, 22);

        jLabel10.setText("COMPLEMENTO");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 30, 141, 16);

        TxComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxComplementoActionPerformed(evt);
            }
        });
        TxComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxComplementoKeyReleased(evt);
            }
        });
        jPanel1.add(TxComplemento);
        TxComplemento.setBounds(420, 50, 210, 22);

        jLabel11.setText("BAIRRO");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(124, 101, 95, 16);

        TxBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxBairroActionPerformed(evt);
            }
        });
        jPanel1.add(TxBairro);
        TxBairro.setBounds(120, 120, 188, 22);

        jLabel12.setText("UF");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 100, 60, 16);

        TxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxUFActionPerformed(evt);
            }
        });
        jPanel1.add(TxUF);
        TxUF.setBounds(320, 120, 90, 22);

        jLabel13.setText("CIDADE");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 100, 86, 16);
        jPanel1.add(TxCidade);
        TxCidade.setBounds(420, 120, 208, 22);

        jLabel14.setText("DDD");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(17, 167, 56, 16);

        TxDDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxDDDActionPerformed(evt);
            }
        });
        TxDDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxDDDKeyTyped(evt);
            }
        });
        jPanel1.add(TxDDD);
        TxDDD.setBounds(17, 189, 55, 22);

        jLabel15.setText("TELEFONE");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(79, 167, 77, 16);

        TxTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxTelefoneKeyTyped(evt);
            }
        });
        jPanel1.add(TxTelefone);
        TxTelefone.setBounds(78, 189, 111, 22);

        TxNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(TxNumero);
        TxNumero.setBounds(20, 120, 90, 22);

        jLabel16.setText("NÚMERO");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(17, 101, 95, 16);

        BtSalvar.setBackground(new java.awt.Color(255, 255, 255));
        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salvar.png"))); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.setToolTipText("SALVAR");
        BtSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BtSalvar);
        BtSalvar.setBounds(230, 180, 130, 40);

        BtFechar.setBackground(new java.awt.Color(255, 255, 255));
        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGINS.png"))); // NOI18N
        BtFechar.setText("Fechar");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });
        jPanel1.add(BtFechar);
        BtFechar.setBounds(370, 180, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 210, 680, 240);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMAÇÕES PESSOAIS"));
        jPanel2.setLayout(null);

        jLabel1.setText("NOME COMPLETO");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(17, 29, 210, 16);

        TxNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxNomeKeyReleased(evt);
            }
        });
        jPanel2.add(TxNome);
        TxNome.setBounds(17, 51, 352, 22);

        jLabel2.setText("CPF/CNPJ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(381, 29, 108, 16);

        TxCPF.setCaretColor(new java.awt.Color(245, 6, 6));
        TxCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxCPFKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxCPFKeyPressed(evt);
            }
        });
        jPanel2.add(TxCPF);
        TxCPF.setBounds(381, 51, 169, 22);

        jLabel3.setText("RG");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(561, 29, 50, 16);

        TxRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxRGKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxRGKeyTyped(evt);
            }
        });
        jPanel2.add(TxRG);
        TxRG.setBounds(562, 51, 101, 22);

        jLabel4.setText("ENTIDADE");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(17, 101, 91, 16);

        CbEntidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ODB", "GOVERNAMENTAL" }));
        CbEntidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbEntidadeActionPerformed(evt);
            }
        });
        jPanel2.add(CbEntidade);
        CbEntidade.setBounds(17, 125, 160, 22);

        jLabel5.setText("USUÁRIO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(183, 101, 100, 16);

        TxUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxUsuarioKeyReleased(evt);
            }
        });
        jPanel2.add(TxUsuario);
        TxUsuario.setBounds(183, 123, 165, 22);

        jLabel6.setText("SENHA");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(360, 100, 74, 16);
        jPanel2.add(TxSenha);
        TxSenha.setBounds(360, 123, 100, 22);

        jLabel7.setText("EMAIL");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(472, 101, 71, 16);
        jPanel2.add(TxEmail);
        TxEmail.setBounds(472, 123, 191, 22);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setForeground(new java.awt.Color(255, 51, 51));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("*");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(460, 120, 10, 20);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setForeground(new java.awt.Color(255, 51, 51));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("*");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(370, 50, 10, 20);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setForeground(new java.awt.Color(255, 51, 51));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("*");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(550, 50, 10, 20);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setForeground(new java.awt.Color(255, 51, 51));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("*");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(350, 120, 10, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 20, 680, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        // TODO add your handling code here:
        
        try{
            
            if(!TxCep.getText().equals("")){
                ODB_BuscaCEP busca = new ODB_BuscaCEP();
                busca.BuscaCEP(TxCep.getText());

                TxCep.setText(ODB_BuscaCEP._Cep_.replace("-", ""));
                TxEndereco.setText(ODB_BuscaCEP.Endereco.toUpperCase());
                TxBairro.setText(ODB_BuscaCEP.Bairro.toUpperCase());
                TxUF.setText(ODB_BuscaCEP.UF.toUpperCase());
                TxCidade.setText(ODB_BuscaCEP.Cidade.toUpperCase());
                TxDDD.setText(ODB_BuscaCEP.DDD);
        
            }else{

                throw new Exception("FAVOR INFORME UM CEP VÁLIDO");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERRO de conexão", JOptionPane.INFORMATION_MESSAGE);
        }
            

    }//GEN-LAST:event_BtBuscarActionPerformed

    private void CbEntidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbEntidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbEntidadeActionPerformed

    private void TxComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxComplementoActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        // TODO add your handling code here
        this.dispose();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void TxEnderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxEnderecoKeyReleased
         if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
                TxEndereco.setText(TxEndereco.getText().toUpperCase());
                }
    }//GEN-LAST:event_TxEnderecoKeyReleased

    private void TxComplementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxComplementoKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
                TxComplemento.setText(TxComplemento.getText().toUpperCase());
                }
    }//GEN-LAST:event_TxComplementoKeyReleased

    private void TxNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxNomeKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
                TxNome.setText(TxNome.getText().toUpperCase());
                }
    }//GEN-LAST:event_TxNomeKeyReleased

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try{
            
            ODB_Usuarios _usuarios = new ODB_Usuarios();
            
            if(TxNome.getText().equals("") && TxCPF.getText().equals("") && TxUsuario.getText().equals("")&&TxSenha.getText().equals("")&&TxEmail.getText().equals("")){
                throw new Exception("EXITEM CAMPOS OBRIGATÓRIOS NÃO PREENCHIDOS, FAVOR VERIFIQUE");
            }else{
                
                _usuarios.setNome(TxNome.getText());
                _usuarios.setCPFCNPJ(TxCPF.getText());
                _usuarios.setRG(TxRG.getText());
                _usuarios.setEntidade(CbEntidade.getSelectedItem().toString());
                _usuarios.setUsuario(TxUsuario.getText());
                _usuarios.setSenha(Criptografia.Cripto(TxSenha.getText()));
                _usuarios.setEmail(TxEmail.getText());
                if(TxCep.getText().equals("")){
                _usuarios.setCep(0);    
                }else{
                _usuarios.setCep((Integer.parseInt(TxCep.getText())));}
                _usuarios.setEndereco(TxEndereco.getText());
                _usuarios.setComplemento(TxComplemento.getText());
                if(TxNumero.getText().equals("")){
                    _usuarios.setNumero(0);
                }else{
                _usuarios.setNumero(Integer.parseInt(TxNumero.getText()));}
                _usuarios.setBairro(TxBairro.getText());
                _usuarios.setUF(TxUF.getText());
                _usuarios.setCidade(TxCidade.getText());
                if(TxDDD.getText().equals("")){
                    _usuarios.setDDD(0);
                }else{
                _usuarios.setDDD(Integer.parseInt(TxDDD.getText()));}
                _usuarios.setTelefone(Integer.parseInt(TxTelefone.getText()));
                _usuarios.setLiberado(false);
                _usuarios.setDataCriacao(new java.sql.Date(Calendar.getInstance().getTimeInMillis()));
                _usuarios.setDataLiberacao(new java.sql.Date(Calendar.getInstance().getTimeInMillis()));
                _usuarios.setLiberadorPor(0);
                _usuarios.setPC(ODB_Host.Pegar_Host());
                _usuarios.setIP(ODB_Host.Pegar_IP());


                Inserir.Criar_Usuarios(_usuarios);
            }
            

            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void TxCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxCPFKeyTyped

    private void TxRGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxRGKeyTyped
        // TODO add your handling code here
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxRGKeyTyped

    private void TxCepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCepKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxCepKeyTyped

    private void TxDDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxDDDKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxDDDKeyTyped

    private void TxTelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxTelefoneKeyTyped
        // TODO add your handling code here:
        int ascii = evt.getKeyChar();
        
        if (!(ascii >= 48 && ascii <=57) && !(ascii == evt.VK_BACK_SPACE)){                        

                        evt.consume() ;

        }
    }//GEN-LAST:event_TxTelefoneKeyTyped

    private void TxDDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxDDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxDDDActionPerformed

    private void TxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxUFActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_TxUFActionPerformed

    private void TxNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxNumeroActionPerformed

    private void TxBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxBairroActionPerformed

    private void TxCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxCPFKeyPressed
        // TODO add your handling code here:
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(TxCPF.getText().isEmpty()){
                    
                    throw new Exception("CAMPO CPF/CNPJ NÃO PODE SER NULO, FAVOR VERIFIQUE");
                    
                }else{
                    
                    ODB_Validador valida = new ODB_Validador();
                    
                    if(TxCPF.getText().trim().length() == 11)
                    {
                        Boolean RetornoCPF = valida.isCPF(TxCPF.getText());

                        if(RetornoCPF.equals(false)){

                            throw new Exception("CPF INVÁLIDO, FAVOR VERIFIQUE");
                        }
                        else{

                            TxRG.isCursorSet();
                        }
                    }else if (TxCPF.getText().trim().length() == 14){
                        
                        Boolean RetornoCNPJ = valida.isCNPJ(TxCPF.getText());
                        
                        if(RetornoCNPJ.equals(false)){
                            throw new Exception("CNPJ INVÁLIDO, FAVOR VERIFIQUE");
                        }else{
                            TxRG.isCursorSet();
                        }
                    }else{
                        throw new Exception("CNPJ OU CNPJ INVÁLIDO");
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TxCPFKeyPressed

    private void TxRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxRGKeyPressed
        // TODO add your handling code here:
        try{
            
            ODB_Validador valida = new ODB_Validador();
            
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                
                if(TxRG.getText() != ""){
                    
                }
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TxRGKeyPressed

    private void TxUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxUsuarioKeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
                TxUsuario.setText(TxUsuario.getText().toUpperCase());
                }
    }//GEN-LAST:event_TxUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JComboBox<String> CbEntidade;
    private javax.swing.JTextField TxBairro;
    private javax.swing.JTextField TxCPF;
    private javax.swing.JTextField TxCep;
    private javax.swing.JTextField TxCidade;
    private javax.swing.JTextField TxComplemento;
    private javax.swing.JTextField TxDDD;
    private javax.swing.JTextField TxEmail;
    private javax.swing.JTextField TxEndereco;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxNumero;
    private javax.swing.JTextField TxRG;
    private javax.swing.JPasswordField TxSenha;
    private javax.swing.JTextField TxTelefone;
    private javax.swing.JTextField TxUF;
    private javax.swing.JTextField TxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
