/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import Banco.Selecionar;
import Classes.Conexao;
import Classes.Criptografia;
import Classes.ODB_Host;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Administrador
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        try{
            UIManager.setLookAndFeel("com.Sun.Java.swing.plaf.nimbus.NimbusLookAndFeel");
        }catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxLogin = new javax.swing.JTextField();
        BtSair = new javax.swing.JButton();
        BtLogar = new javax.swing.JButton();
        TxSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odb/ordem-dos-detetives-do-brasil-logo-3B53A4A435-seeklogo.com.jpg"))); // NOI18N
        getContentPane().add(LbFoto);
        LbFoto.setBounds(10, 10, 300, 280);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACESSO RESTRITO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 20, 240, 20);

        jLabel2.setText("SENHA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 120, 170, 16);

        jLabel3.setText("USUARIO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 70, 170, 16);

        TxLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxLoginKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxLoginKeyReleased(evt);
            }
        });
        getContentPane().add(TxLogin);
        TxLogin.setBounds(360, 90, 170, 22);

        BtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGINS.png"))); // NOI18N
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });
        getContentPane().add(BtSair);
        BtSair.setBounds(440, 200, 50, 40);

        BtLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remover-usuario.png"))); // NOI18N
        BtLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLogarActionPerformed(evt);
            }
        });
        getContentPane().add(BtLogar);
        BtLogar.setBounds(390, 200, 40, 40);

        TxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxSenhaActionPerformed(evt);
            }
        });
        TxSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(TxSenha);
        TxSenha.setBounds(360, 150, 170, 22);

        jLabel4.setForeground(new java.awt.Color(17, 13, 245));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ESQUECI MINHA SENHA");
        jLabel4.setToolTipText("ESQUI MINHA SENHA");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 280, 200, 20);

        jLabel5.setForeground(new java.awt.Color(6, 6, 245));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SOLICITAR ACESSO");
        jLabel5.setToolTipText("SOLICITAR ACESSO AO SISTEMA]");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 250, 200, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mostrar-senha.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 140, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/remover-usuario.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 80, 40, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_BtSairActionPerformed

    static final String curDir = System.getProperty("user.dir") + "\\odb.fw.png";
    
    private void BtLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLogarActionPerformed
        try{
            
            if(TxLogin.getText().equals("") && TxSenha.getText().equals(""))
            {
                throw new Exception("LOGIN OU SENHA INVALIDA");
                
            }else
            {
                Boolean LoginAtivo = Selecionar.Consultar_Login(TxLogin.getText(), Criptografia.Cripto(TxSenha.getText()));
                
                if(LoginAtivo.equals(false)){
                    
                    throw new Exception("LOGIN OU SENHA INVÁLIDA OU SEU ACESSO AINDA NÃO ESTÁ HABILITADO, FAVOR ENTRAR EM CONTATO");
                }
                else{
                    
                    Principal frm = new Principal();
                    frm.setSize(1000, 600);
                    frm.getContentPane().setBackground(Color.white);
                    frm.setResizable(false);
                    frm.setLocationRelativeTo(null);
                    frm.setIconImage(Toolkit.getDefaultToolkit().getImage(curDir));
                    frm.show();
                    this.setVisible(false);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtLogarActionPerformed

    private void TxLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxLoginKeyReleased
        if ((evt.getKeyCode() != KeyEvent.VK_HOME) && evt.getKeyCode() != KeyEvent.VK_LEFT && evt.getKeyCode() != KeyEvent.VK_RIGHT) {
                TxLogin.setText(TxLogin.getText().toUpperCase());
                }
    }//GEN-LAST:event_TxLoginKeyReleased

    private void TxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxSenhaActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        FrmUsuario frm = new FrmUsuario();
        frm.setSize(700, 480);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void TxLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxLoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            TxSenha.requestFocus();
        }
    }//GEN-LAST:event_TxLoginKeyPressed

    private void TxSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxSenhaKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                if(TxLogin.getText().equals("") && TxSenha.getText().equals(""))
                {
                    throw new Exception("LOGIN OU SENHA INVALIDA");

                }else
                {
                    Boolean LoginAtivo = Selecionar.Consultar_Login(TxLogin.getText(), Criptografia.Cripto(TxSenha.getText()));

                    if(LoginAtivo.equals(false)){

                        throw new Exception("LOGIN OU SENHA INVÁLIDA OU SEU ACESSO AINDA NÃO ESTÁ HABILITADO, FAVOR ENTRAR EM CONTATO");
                    }
                    else{

                        Principal frm = new Principal();
                        frm.setSize(1000, 600);
                        frm.getContentPane().setBackground(Color.white);
                        frm.setResizable(false);
                        frm.setLocationRelativeTo(null);
                        frm.setIconImage(Toolkit.getDefaultToolkit().getImage(curDir));
                        frm.show();
                        this.setVisible(false);
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(),"ERRO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TxSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtLogar;
    private javax.swing.JButton BtSair;
    private javax.swing.JLabel LbFoto;
    private javax.swing.JTextField TxLogin;
    private javax.swing.JPasswordField TxSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
