/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import java.awt.Font;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.Doc;
import javax.print.DocFlavor;
import javax.print.DocPrintJob;
import javax.print.PrintException;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.ServiceUI;
import javax.print.SimpleDoc;
import javax.print.attribute.HashDocAttributeSet;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.FileChooserUI;
import javax.swing.plaf.basic.BasicFileChooserUI;

/**
 *
 * @author fusion
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbFoto = new javax.swing.JLabel();
        BtImprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TxMae = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxNascimento = new javax.swing.JFormattedTextField();
        TxCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxPai = new javax.swing.JTextField();
        TxRegistro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxRG = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxValidade = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        BtFoto = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuArquivo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ODB");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        LbFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sem-foto.jpg"))); // NOI18N
        getContentPane().add(LbFoto);
        LbFoto.setBounds(10, 20, 300, 280);

        BtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DELEGACIA.png"))); // NOI18N
        BtImprimir.setToolTipText("IMPRIMIR");
        BtImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(BtImprimir);
        BtImprimir.setBounds(490, 300, 40, 40);

        jLabel1.setText("DATA DE NASCIMENTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 290, 150, 15);
        getContentPane().add(TxMae);
        TxMae.setBounds(330, 210, 270, 27);

        jLabel3.setText("CPF");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 240, 30, 15);
        getContentPane().add(TxNascimento);
        TxNascimento.setBounds(330, 310, 140, 27);
        getContentPane().add(TxCPF);
        TxCPF.setBounds(480, 260, 120, 27);

        jLabel5.setText("NOME");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 90, 140, 15);
        getContentPane().add(TxNome);
        TxNome.setBounds(330, 110, 270, 27);

        jLabel6.setText("PAI");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 140, 140, 15);
        getContentPane().add(TxPai);
        TxPai.setBounds(330, 160, 270, 27);
        getContentPane().add(TxRegistro);
        TxRegistro.setBounds(330, 60, 140, 27);

        jLabel7.setText("MÃE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 190, 130, 15);

        jLabel8.setText("RG");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 240, 30, 15);
        getContentPane().add(TxRG);
        TxRG.setBounds(330, 260, 140, 27);

        jLabel9.setText("VALIDADE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(480, 40, 100, 15);
        getContentPane().add(TxValidade);
        TxValidade.setBounds(480, 60, 120, 27);

        jLabel10.setText("Nº DE REGISTRO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 40, 130, 15);

        BtFoto.setText("Importar Foto");
        BtFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFotoActionPerformed(evt);
            }
        });
        getContentPane().add(BtFoto);
        BtFoto.setBounds(10, 310, 300, 27);

        MnuArquivo.setText("Arquivo");

        jMenuItem1.setText("Imprimir");
        MnuArquivo.add(jMenuItem1);

        jMenuItem2.setText("Fechar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnuArquivo.add(jMenuItem2);

        jMenuBar1.add(MnuArquivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImprimirActionPerformed
        try
        {
            Properties properties = new Properties();
             PrintJob pj = Toolkit.getDefaultToolkit().getPrintJob(new Frame(), "ODB", properties);
              if (pj != null) {
                   Graphics g = pj.getGraphics();
                   g.setFont(new Font("Arial", Font.PLAIN, 10));
                   g.drawString(TxRegistro.getText(), 10, 50);
                   g.drawString(TxValidade.getText(), 30, 50);
                   g.drawString(TxNome.getText(), 50, 50);
                   g.drawString(TxPai.getText(), 70, 50);
                   g.drawString(TxMae.getText(), 90, 50);
                   g.drawString(TxRG.getText(), 110, 50);
                   g.drawString(TxCPF.getText(), 130, 50);
                   g.drawString(TxNascimento.getText(), 150, 50);
                   g.translate(10, 10);
                   g.dispose();
                   pj.end();
              }
            
        }catch(HeadlessException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO", JOptionPane.PLAIN_MESSAGE);
        } 
    }//GEN-LAST:event_BtImprimirActionPerformed

    private void BtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFotoActionPerformed
        // TODO add your handling code here:
         try
         {
             JFileChooser chooser = new JFileChooser();
             chooser.showOpenDialog(null);
             
             File file = chooser.getSelectedFile();
             String Caminho = file.getAbsolutePath();
             
             LbFoto.setIcon(new ImageIcon(Caminho));
             
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO", JOptionPane.PLAIN_MESSAGE);
         }
        
    }//GEN-LAST:event_BtFotoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtFoto;
    private javax.swing.JButton BtImprimir;
    private javax.swing.JLabel LbFoto;
    private javax.swing.JMenu MnuArquivo;
    private javax.swing.JTextField TxCPF;
    private javax.swing.JTextField TxMae;
    private javax.swing.JFormattedTextField TxNascimento;
    private javax.swing.JTextField TxNome;
    private javax.swing.JTextField TxPai;
    private javax.swing.JTextField TxRG;
    private javax.swing.JTextField TxRegistro;
    private javax.swing.JFormattedTextField TxValidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
