/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odb;

import java.awt.Color;

/**
 *
 * @author Administrador
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BtUsuarios = new javax.swing.JButton();
        BtDetetives = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        BtOuvidoria = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnuCadastro = new javax.swing.JMenu();
        MnuUsuario = new javax.swing.JMenuItem();
        MnuDetetive = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MnuEventos = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MnuFinanceiro = new javax.swing.JMenu();
        MnuContasPagar = new javax.swing.JMenuItem();
        MnuContasReceber = new javax.swing.JMenuItem();
        MnuImpressao = new javax.swing.JMenu();
        mnuCredencial = new javax.swing.JMenuItem();
        MnuConsultas = new javax.swing.JMenu();
        MnuConsultaUsuario = new javax.swing.JMenuItem();
        MnuConsultaDetetives = new javax.swing.JMenuItem();
        MnuHelpDesk = new javax.swing.JMenu();
        MnuConfiguracao = new javax.swing.JMenu();
        MnuAjuda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORDEM DOS DETETIVES DO BRASIL");
        getContentPane().setLayout(null);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        BtUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BtUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CADASTRO.png"))); // NOI18N
        BtUsuarios.setText("USUÁRIOS");
        BtUsuarios.setToolTipText("CADASTRO DE USUÁRIOS");
        BtUsuarios.setFocusable(false);
        BtUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(BtUsuarios);

        BtDetetives.setBackground(new java.awt.Color(255, 255, 255));
        BtDetetives.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CADASTRO.png"))); // NOI18N
        BtDetetives.setText("DETETIVES");
        BtDetetives.setToolTipText("CADASTRO DE DETETIVES");
        BtDetetives.setFocusable(false);
        BtDetetives.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtDetetives.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtDetetives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDetetivesActionPerformed(evt);
            }
        });
        jToolBar1.add(BtDetetives);
        jToolBar1.add(jSeparator3);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FINANCEIRO.png"))); // NOI18N
        jButton3.setText("PAGAR");
        jButton3.setToolTipText("CONTAS A PAGAR");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FINANCEIRO.png"))); // NOI18N
        jButton4.setText("RECEBER");
        jButton4.setToolTipText("CONTAS A RECEBER");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RELATORIO.png"))); // NOI18N
        jButton5.setText("CREDENCIAL");
        jButton5.setToolTipText("IMPRESSÃO DA CREDENCIAL");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator5);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AJUDA.png"))); // NOI18N
        jButton6.setText("AJUDA");
        jButton6.setToolTipText("AJUDA SOBRE O SISTEMA");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DELEGACIA.png"))); // NOI18N
        jButton7.setText("HELPDESK");
        jButton7.setToolTipText("ABERTURA DE CHAMADOS");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton7);

        BtOuvidoria.setBackground(new java.awt.Color(255, 255, 255));
        BtOuvidoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ouvidoria.fw.png"))); // NOI18N
        BtOuvidoria.setText("OUVIDORIA");
        BtOuvidoria.setToolTipText("OUVIDORIA");
        BtOuvidoria.setFocusable(false);
        BtOuvidoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtOuvidoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BtOuvidoria);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SITE.png"))); // NOI18N
        jButton8.setText("SITE");
        jButton8.setToolTipText("ACESSAR O SITE DA ODB");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton8);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1000, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/detetive-para-investigacao-virtual-.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1000, 620);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        MnuCadastro.setBackground(new java.awt.Color(255, 255, 255));
        MnuCadastro.setText("Cadastro");

        MnuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MnuUsuario.setBackground(new java.awt.Color(255, 255, 255));
        MnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CADASTRO.png"))); // NOI18N
        MnuUsuario.setText("Usuario");
        MnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuUsuarioActionPerformed(evt);
            }
        });
        MnuCadastro.add(MnuUsuario);

        MnuDetetive.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MnuDetetive.setBackground(new java.awt.Color(255, 255, 255));
        MnuDetetive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CADASTRO.png"))); // NOI18N
        MnuDetetive.setText("Detetive");
        MnuDetetive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuDetetiveActionPerformed(evt);
            }
        });
        MnuCadastro.add(MnuDetetive);
        MnuCadastro.add(jSeparator1);

        MnuEventos.setBackground(new java.awt.Color(255, 255, 255));
        MnuEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CALENDARIO.png"))); // NOI18N
        MnuEventos.setText("Eventos");
        MnuEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuEventosActionPerformed(evt);
            }
        });
        MnuCadastro.add(MnuEventos);
        MnuCadastro.add(jSeparator6);

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RELATORIO.png"))); // NOI18N
        jMenuItem2.setText("GRUPO");
        MnuCadastro.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RELATORIO.png"))); // NOI18N
        jMenuItem3.setText("ESTADO CIVIL");
        MnuCadastro.add(jMenuItem3);

        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RELATORIO.png"))); // NOI18N
        jMenuItem5.setText("SEXO");
        MnuCadastro.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RELATORIO.png"))); // NOI18N
        jMenuItem6.setText("TIPO CADASTRO");
        MnuCadastro.add(jMenuItem6);

        jMenuBar1.add(MnuCadastro);

        MnuFinanceiro.setText("Financeiro");

        MnuContasPagar.setBackground(new java.awt.Color(255, 255, 255));
        MnuContasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FINANCEIRO.png"))); // NOI18N
        MnuContasPagar.setText("Contas a Pagar");
        MnuFinanceiro.add(MnuContasPagar);

        MnuContasReceber.setBackground(new java.awt.Color(255, 255, 255));
        MnuContasReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FINANCEIRO.png"))); // NOI18N
        MnuContasReceber.setText("Contas a Receber");
        MnuFinanceiro.add(MnuContasReceber);

        jMenuBar1.add(MnuFinanceiro);

        MnuImpressao.setText("Impressão");

        mnuCredencial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnuCredencial.setBackground(new java.awt.Color(255, 255, 255));
        mnuCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RELATORIO.png"))); // NOI18N
        mnuCredencial.setText("Credencial");
        mnuCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCredencialActionPerformed(evt);
            }
        });
        MnuImpressao.add(mnuCredencial);

        jMenuBar1.add(MnuImpressao);

        MnuConsultas.setText("Consultas");

        MnuConsultaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        MnuConsultaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        MnuConsultaUsuario.setText("Usuarios");
        MnuConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuConsultaUsuarioActionPerformed(evt);
            }
        });
        MnuConsultas.add(MnuConsultaUsuario);

        MnuConsultaDetetives.setBackground(new java.awt.Color(255, 255, 255));
        MnuConsultaDetetives.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONSULTA.png"))); // NOI18N
        MnuConsultaDetetives.setText("Detetives");
        MnuConsultas.add(MnuConsultaDetetives);

        jMenuBar1.add(MnuConsultas);

        MnuHelpDesk.setText("Relatórios");
        jMenuBar1.add(MnuHelpDesk);

        MnuConfiguracao.setText("Configuração");

        MnuAjuda.setBackground(new java.awt.Color(255, 255, 255));
        MnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CONFIGURACAO.png"))); // NOI18N
        MnuAjuda.setText("Sistema");
        MnuConfiguracao.add(MnuAjuda);

        jMenuBar1.add(MnuConfiguracao);

        jMenu1.setText("Ajuda");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AJUDA.png"))); // NOI18N
        jMenuItem1.setText("Sobre");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/INVESTIGACAO.png"))); // NOI18N
        jMenuItem4.setText("HelpDesk");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCredencialActionPerformed
         Main frm = new Main();
        frm.setSize(630, 400);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_mnuCredencialActionPerformed

    private void MnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuUsuarioActionPerformed
        FrmUsuario frm = new FrmUsuario();
        frm.setSize(700, 480);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_MnuUsuarioActionPerformed

    private void BtUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtUsuariosActionPerformed
        // TODO add your handling code here:
        FrmUsuario frm = new FrmUsuario();
        frm.setSize(700, 480);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_BtUsuariosActionPerformed

    private void MnuConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuConsultaUsuarioActionPerformed
        FrmConsultarUsuarios frm = new FrmConsultarUsuarios();
        frm.setSize(800, 550);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_MnuConsultaUsuarioActionPerformed

    private void BtDetetivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDetetivesActionPerformed
        // TODO add your handling code here:
        FrmDetetive frm = new FrmDetetive();
        frm.setSize(880, 515);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_BtDetetivesActionPerformed

    private void MnuDetetiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuDetetiveActionPerformed
        // TODO add your handling code here:
        FrmDetetive frm = new FrmDetetive();
        frm.setSize(880, 515);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_MnuDetetiveActionPerformed

    private void MnuEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuEventosActionPerformed
                // TODO add your handling code here:
        FrmEventos frm = new FrmEventos();
        frm.setSize(705, 700);
        frm.getContentPane().setBackground(Color.white);
        frm.setResizable(false);
        frm.setLocationRelativeTo(null);
        frm.show();
    }//GEN-LAST:event_MnuEventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtDetetives;
    private javax.swing.JButton BtOuvidoria;
    private javax.swing.JButton BtUsuarios;
    private javax.swing.JMenuItem MnuAjuda;
    private javax.swing.JMenu MnuCadastro;
    private javax.swing.JMenu MnuConfiguracao;
    private javax.swing.JMenuItem MnuConsultaDetetives;
    private javax.swing.JMenuItem MnuConsultaUsuario;
    private javax.swing.JMenu MnuConsultas;
    private javax.swing.JMenuItem MnuContasPagar;
    private javax.swing.JMenuItem MnuContasReceber;
    private javax.swing.JMenuItem MnuDetetive;
    private javax.swing.JMenuItem MnuEventos;
    private javax.swing.JMenu MnuFinanceiro;
    private javax.swing.JMenu MnuHelpDesk;
    private javax.swing.JMenu MnuImpressao;
    private javax.swing.JMenuItem MnuUsuario;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuCredencial;
    // End of variables declaration//GEN-END:variables
}
